name: Docker Build & Publish

on:
    push:
        branches:
            - main

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        steps:
            - name: Clonar mi repositorio
              uses: actions/checkout@v4

            - name: Login a Docker Hub
              run: docker login -u ${{ secrets.DOCKER_USER }} -p "${{ secrets.DOCKER_PASSWORD }}"

            - name: Crear la imagen
              run: docker build -t juanfr97/music-api-411:latest .

            - name: Publicar imagen
              run: docker push juanfr97/music-api-411:latest